version: "2.0"

services:
  web:
    build: web
    container_name: fwportal_app
    #image: ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:latest
    restart: always
    ports: 
      - 8001:80
      - 5000-5100:5000-5100

#  nginx:
#      build: nginx
#      container_name: fwportal_nginx
#      restart: always
#      ports:
#        - 80:80
