# Generated by Django 3.2.9 on 2021-11-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_backuppolicy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuppolicy',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backuppolicy',
            name='run_hour',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='backuppolicy',
            name='run_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
