# Generated by Django 3.2.9 on 2021-11-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_alter_backup_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backuppolicy',
            old_name='run_minutes',
            new_name='run_minute',
        ),
        migrations.AddField(
            model_name='backuppolicy',
            name='run_cycle',
            field=models.CharField(choices=[('DAILY', 'daily'), ('HOURLY', 'hourly'), ('WEEKLY', 'weekly'), ('MONTLY', 'montly')], default='daily', max_length=10),
        ),
    ]
