# Generated by Django 3.2.9 on 2021-11-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField(max_length=100)),
                ('admin_user', models.CharField(max_length=20)),
                ('admin_pass', models.CharField(max_length=40)),
            ],
        ),
    ]
