# Generated by Django 3.2.9 on 2022-06-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='api_key',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
