# Generated by Django 3.2.9 on 2022-06-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0003_firewall_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='user_reverse_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
