# Generated by Django 3.2.9 on 2022-06-08 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0004_firewall_user_reverse_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewall',
            name='admin_pass',
        ),
        migrations.RemoveField(
            model_name='firewall',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='firewall',
            name='url',
        ),
        migrations.AddField(
            model_name='firewall',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
