# Generated by Django 3.2.9 on 2022-06-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0005_auto_20220607_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
