# Generated by Django 3.2.9 on 2022-06-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0006_alter_firewall_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='control_channel_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
